CREATE TABLE IF NOT EXISTS motoristas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(180) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ajudantes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(180) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS cidades (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(180) NOT NULL,
    estado VARCHAR(2),
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS hoteis (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(220) NOT NULL,
    cidade_id INTEGER REFERENCES cidades(id) ON DELETE RESTRICT,
    telefone VARCHAR(40),
    observacao TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS importacoes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arquivo VARCHAR(255),
    abas TEXT,
    usuario_id INTEGER,
    qtd_importados INTEGER NOT NULL DEFAULT 0,
    qtd_atualizados INTEGER NOT NULL DEFAULT 0,
    qtd_ignorados INTEGER NOT NULL DEFAULT 0,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS reservas_hotel (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_reserva DATE NOT NULL,
    motorista VARCHAR(180),
    ajudante VARCHAR(180),
    cidade VARCHAR(180),
    hotel_pousada VARCHAR(220),
    tipo VARCHAR(120),
    valor NUMERIC(12, 2),
    dias INTEGER NOT NULL CHECK (dias > 0),
    nao_planejada BOOLEAN NOT NULL DEFAULT FALSE,
    categoria VARCHAR(120),
    observacao TEXT,
    criado_por INTEGER,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    importacao_id INTEGER REFERENCES importacoes(id) ON DELETE SET NULL
);

ALTER TABLE reservas_hotel
    ALTER COLUMN motorista DROP NOT NULL,
    ALTER COLUMN cidade DROP NOT NULL,
    ALTER COLUMN hotel_pousada DROP NOT NULL,
    ALTER COLUMN valor DROP NOT NULL;

ALTER TABLE reservas_hotel DROP CONSTRAINT IF EXISTS reservas_hotel_valor_check;

CREATE INDEX IF NOT EXISTS idx_reservas_data_reserva ON reservas_hotel (data_reserva);
CREATE INDEX IF NOT EXISTS idx_reservas_motorista ON reservas_hotel (motorista);
CREATE INDEX IF NOT EXISTS idx_reservas_ajudante ON reservas_hotel (ajudante);
CREATE INDEX IF NOT EXISTS idx_reservas_cidade ON reservas_hotel (cidade);
CREATE INDEX IF NOT EXISTS idx_reservas_hotel_pousada ON reservas_hotel (hotel_pousada);
CREATE INDEX IF NOT EXISTS idx_reservas_categoria ON reservas_hotel (categoria);
CREATE INDEX IF NOT EXISTS idx_motoristas_nome_lower ON motoristas (LOWER(nome));
CREATE INDEX IF NOT EXISTS idx_ajudantes_nome_lower ON ajudantes (LOWER(nome));
CREATE INDEX IF NOT EXISTS idx_cidades_nome_lower ON cidades (LOWER(nome));
CREATE INDEX IF NOT EXISTS idx_hoteis_nome_lower ON hoteis (LOWER(nome));
CREATE INDEX IF NOT EXISTS idx_hoteis_cidade_id ON hoteis (cidade_id);

CREATE OR REPLACE FUNCTION set_reservas_atualizado_em()
RETURNS TRIGGER AS $$
BEGIN
    NEW.atualizado_em = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'trg_reservas_hotel_atualizado_em'
    ) THEN
        CREATE TRIGGER trg_reservas_hotel_atualizado_em
        BEFORE UPDATE ON reservas_hotel
        FOR EACH ROW
        EXECUTE FUNCTION set_reservas_atualizado_em();
    END IF;
END;
$$;
